brew 'coreutils'
brew 'git'
brew 'icu4c'
brew 'mas'
brew 'mongodb'
brew 'node'
brew 'openssl'
brew 'pkg-config'
brew 'postgresql'
brew 'python'
brew 'python@2'
brew 'rbenv'
brew 'readline'
brew 'sqlite'
brew 'tree'
brew 'xz'
brew 'zsh'

cask 'carbon-copy-cloner'
cask 'dashlane'
cask 'discord'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
# cask 'karabiner' #macOS shortcut manager
cask 'postgres'
cask 'postman'
cask 'robo-3t'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'visual-studio-code'

# mas 'Bear', id: 409201541
# mas 'Numbers', id: 409203825
# mas 'Pages', id: 409201541
# mas 'Xcode', id: 497799835
