#!/bin/zsh
set -e

# System Preferences > Dock > Automatically hide and show the Dock:
defaults write com.apple.dock autohide -bool true

### Finder Preferences ###
# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

#cloning with "--recurse-submodules" vs. "--recursive"
mkdir -p ~/.zprezto
cd ~/.zprezto
if [ -d .git ]; then
    git pull --recurse-submodules
else
    git clone --recurse-submodules https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi;

setopt EXTENDED_GLOB
#for every file in runcoms except for README.md
#symlink into home directory
for rcfile in ~/.zprezto/runcoms/^README.md(.N); do
  ln -sfn "$rcfile" ~/.${rcfile:t}
done

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/.dotfiles/dot/*); do ln -sfn $f ~/.$(basename $f); done

echo "Successful setup"
