#!/bin/bash
set -e

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/.dotfiles/dot/*); do ln -sfn $f ~/.$(basename $f); done

# Symlink files/* into home directory as regular files
# for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done

#Spectacle
ln -sfn ~/.dotfiles/programs/spectacle/shortcuts.json ~/Library/Application\ Support/Spectacle/Shortcuts.json