#!/bin/zsh
set -e

# After brew installed goes here!

# Symlink files/* into home directory as regular files
# for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done

# Hammerspoon
hammerspoondir=~/.hammerspoon
mkdir -p $hammerspoondir
# Create the spoons directory
spoonsdir="$hammerspoondir/Spoons"
mkdir -p $spoonsdir

# download and copy over spoon installation manager
echo "downloading SpoonInstall"
installfile=SpoonInstall.spoon.zip
wget "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/$installfile"
# unzip and replace contents of existing SpoonInstall folder if present
unzip -o $installfile -d $spoonsdir
rm -f $installfile

# symlink the init.lua
ln -sfn ~/.dotfiles/programs/hammerspoon/init.lua "$hammerspoondir/init.lua"

# Visual Studio Code
mkdir -p ~/Library/Application\ Support/Code/User
for f in $(ls -d ~/.dotfiles/programs/code/*.json); do ln -sfn $f ~/Library/Application\ Support/Code/User/$(basename $f); done
# install extensions
cat ~/.dotfiles/programs/code/extensions.txt | xargs -L 1 code --install-extension

# Set shell to be homebrew installed zsh
sudo dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh
echo "Successful after-setup"
