#!/bin/zsh
set -e

# After brew installed goes here!
# cat << EOF >> ~/.bash_profile
# Add Visual Studio Code (code)
# export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
#EOF

# Symlink files/* into home directory as regular files
# for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done

# Spectacle
mkdir -p ~/Library/Application\ Support/Spectacle
ln -sfn ~/.dotfiles/programs/spectacle/shortcuts.json ~/Library/Application\ Support/Spectacle/Shortcuts.json

# Visual Studio Code
mkdir -p ~/Library/Application\ Support/Code/User
for f in $(ls -d ~/.dotfiles/programs/code/*.json); do ln -sfn $f ~/Library/Application\ Support/Code/User/$(basename $f); done
# install extensions
cat ~/.dotfiles/programs/code/extensions.txt | xargs -L 1 code --install-extension

# Set shell to be homebrew installed zsh
sudo dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh
echo "Successful after-setup"
